# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Marco Zone
email: hallo@marco.zone
description: > # this means to ignore newlines until "baseurl:"
  Meinungen zu kram mit denen sich keiner so viel beschäftigen will.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.marco.zone" # the base hostname & protocol for your site, e.g. http://example.com

website_schema:
  "@context": http://schema.org
  "@type": WebSite
  name: Marco Zone
  alternateName: Die Marco Zone
  url: https://www.marco.zone/

authors:
  marco:
    name: Marco Pfeiffer
    twitter: "@TheTrueMemo"

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
permalink: /:title
defaults:
  -
    scope:
      path: ""
    values:
      layout:     base
      author:     marco
      language:   de
      analytics:
        vars:
          account: UA-60388424-1
          # as far as i can tell, google analytics is automatically anonymized in amp
          # https://support.google.com/analytics/answer/6343176?hl=en&vid=0-679344420636-1488275777141
        triggers:
          pageview: {"on": visible, request: pageview}
          headerLinkClick: {"on": click, request: event, selector: "#page-header a[href]", vars: {eventCategory: header, eventAction: click-link}}
          footerLinkClick: {"on": click, request: event, selector: "#page-footer a[href]", vars: {eventCategory: footer, eventAction: click-link}}
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout:     post
      priority:   0.75
      og: {"type": "article"}
      analytics:
        triggers:
          articleLinkClick: {"on": click, request: event, selector: "[itemprop=articleBody] a[href]", vars: {eventCategory: article, eventAction: click-link}}
          scroll25: {"on": scroll, request: event, scrollSpec: {verticalBoundaries: [25]}, vars: {eventCategory: article, eventAction: scroll, eventValue: 25}}
          scroll50: {"on": scroll, request: event, scrollSpec: {verticalBoundaries: [50]}, vars: {eventCategory: article, eventAction: scroll, eventValue: 50}}
          scroll75: {"on": scroll, request: event, scrollSpec: {verticalBoundaries: [75]}, vars: {eventCategory: article, eventAction: scroll, eventValue: 75}}

hyphenate_filter:
  language: de
  selector: p
  left: 4
  right: 3

include:
  - _redirects
  - _headers