# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Marco Zone
email: hallo@marco.zone
description: > # this means to ignore newlines until "baseurl:"
  Meinungen zu kram mit denen sich keiner so viel beschäftigen will.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.marco.zone" # the base hostname & protocol for your site, e.g. http://example.com
url2: "https://marco-zone.netlify.com" # amp requires a secondary domain for iframes to work correctly. This is it

website_schema:
  "@context": http://schema.org
  "@type": WebSite
  name: Marco Zone
  alternateName: Die Marco Zone
  url: https://www.marco.zone/
  sameAs: https://twitter.com/TheTrueNemo

# Build settings
timezone: Europe/Berlin
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - docker-compose.yml
permalink: /:title

sass:
  style: compressed

responsive_image:
  template: _includes/image.html
  default_quality: 80
  sizes:
    - width: 240 # icon version (2x but it isn't worth making a 1x variant)
    - width: 540 # 1x in content
    - width: 1080 # 2x in content
      quality: 70
  auto_rotate: false
  base_path: assets
  output_path_format: assets/resized/%{width}/%{basename}

include:
  - _redirects
  - _headers

# defaults

defaults:
  -
    scope:
      path: ""
    values:
      layout:     base
      author:     marco
      language:   en
  -
    scope:
      path: "meta"
    values:
      layout: null
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      og: {"type": "article"}
